### ISSUE TITLE
Making decrypt accessible

### ISSUE THREAD

**Issue by emitanaka** [dicook/nullabor#19]
At the moment the decryption of `lineup()` is printed as a message and it's hard to capture it programmatically. I wonder perhaps saving this to `.Last.value` or some special function to extract it will be useful? (Or maybe there is one already?)

**Comment by dicook** [comment]
Yes, it's been an issue. We had looked at this before but there wasn't a good way to do this. 

The best approach is to generate the position outside of the lineup function, and pass it in with the `pos` argument.

**Comment by emitanaka** [comment]
You can just add it as an attribute to the object.
