### ISSUE TITLE
Better hashing for decrypt()

### ISSUE THREAD

**Issue by AmeliaMN** [dicook/nullabor#4]
The first ~20 characters are just the phrase "True data in position" (this is always hashed the same way, at least on the same computer, I think) and the last 1 to 2 are the number. If you get, for example, "WOXC 1IZI Tx t4nTZT4x iV" you know the true data is in one of the two-digit number plots. I think this might give you a subconscious cue to where the real plot is.

**Comment by dicook** [comment]
thx, will fix this, hopefully today

**Comment by dicook** [comment]
fixed
